//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTiendaTest.ProductoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int co_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nu_precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tx_descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int co_producto {
            get {
                return this.co_productoField;
            }
            set {
                if ((this.co_productoField.Equals(value) != true)) {
                    this.co_productoField = value;
                    this.RaisePropertyChanged("co_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nu_precio {
            get {
                return this.nu_precioField;
            }
            set {
                if ((this.nu_precioField.Equals(value) != true)) {
                    this.nu_precioField = value;
                    this.RaisePropertyChanged("nu_precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tx_descripcion {
            get {
                return this.tx_descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.tx_descripcionField, value) != true)) {
                    this.tx_descripcionField = value;
                    this.RaisePropertyChanged("tx_descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteInexistenteError", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Errores")]
    [System.SerializableAttribute()]
    public partial class ClienteInexistenteError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoWS.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/CrearProducto", ReplyAction="http://tempuri.org/IProductoService/CrearProductoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTiendaTest.ProductoWS.ClienteInexistenteError), Action="http://tempuri.org/IProductoService/CrearProductoClienteInexistenteErrorFault", Name="ClienteInexistenteError", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Errores")]
        WCFTiendaTest.ProductoWS.Producto CrearProducto(WCFTiendaTest.ProductoWS.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/CrearProducto", ReplyAction="http://tempuri.org/IProductoService/CrearProductoResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> CrearProductoAsync(WCFTiendaTest.ProductoWS.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoService/ObtenerProductoResponse")]
        WCFTiendaTest.ProductoWS.Producto ObtenerProducto(int co_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoService/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> ObtenerProductoAsync(int co_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ModificarProducto", ReplyAction="http://tempuri.org/IProductoService/ModificarProductoResponse")]
        WCFTiendaTest.ProductoWS.Producto ModificarProducto(WCFTiendaTest.ProductoWS.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ModificarProducto", ReplyAction="http://tempuri.org/IProductoService/ModificarProductoResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> ModificarProductoAsync(WCFTiendaTest.ProductoWS.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/EliminarProducto", ReplyAction="http://tempuri.org/IProductoService/EliminarProductoResponse")]
        void EliminarProducto(WCFTiendaTest.ProductoWS.Producto productoAEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/EliminarProducto", ReplyAction="http://tempuri.org/IProductoService/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(WCFTiendaTest.ProductoWS.Producto productoAEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarProductos", ReplyAction="http://tempuri.org/IProductoService/ListarProductosResponse")]
        WCFTiendaTest.ProductoWS.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarProductos", ReplyAction="http://tempuri.org/IProductoService/ListarProductosResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto[]> ListarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : WCFTiendaTest.ProductoWS.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<WCFTiendaTest.ProductoWS.IProductoService>, WCFTiendaTest.ProductoWS.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTiendaTest.ProductoWS.Producto CrearProducto(WCFTiendaTest.ProductoWS.Producto productoACrear) {
            return base.Channel.CrearProducto(productoACrear);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> CrearProductoAsync(WCFTiendaTest.ProductoWS.Producto productoACrear) {
            return base.Channel.CrearProductoAsync(productoACrear);
        }
        
        public WCFTiendaTest.ProductoWS.Producto ObtenerProducto(int co_producto) {
            return base.Channel.ObtenerProducto(co_producto);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> ObtenerProductoAsync(int co_producto) {
            return base.Channel.ObtenerProductoAsync(co_producto);
        }
        
        public WCFTiendaTest.ProductoWS.Producto ModificarProducto(WCFTiendaTest.ProductoWS.Producto productoAModificar) {
            return base.Channel.ModificarProducto(productoAModificar);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto> ModificarProductoAsync(WCFTiendaTest.ProductoWS.Producto productoAModificar) {
            return base.Channel.ModificarProductoAsync(productoAModificar);
        }
        
        public void EliminarProducto(WCFTiendaTest.ProductoWS.Producto productoAEliminar) {
            base.Channel.EliminarProducto(productoAEliminar);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(WCFTiendaTest.ProductoWS.Producto productoAEliminar) {
            return base.Channel.EliminarProductoAsync(productoAEliminar);
        }
        
        public WCFTiendaTest.ProductoWS.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.ProductoWS.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
    }
}
