//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTiendaTest.VentasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int co_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nu_cantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int co_producto {
            get {
                return this.co_productoField;
            }
            set {
                if ((this.co_productoField.Equals(value) != true)) {
                    this.co_productoField = value;
                    this.RaisePropertyChanged("co_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nu_cantidad {
            get {
                return this.nu_cantidadField;
            }
            set {
                if ((this.nu_cantidadField.Equals(value) != true)) {
                    this.nu_cantidadField = value;
                    this.RaisePropertyChanged("nu_cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venta", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Venta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTiendaTest.VentasWS.Item[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dt_fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTiendaTest.VentasWS.Cliente nu_rucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nu_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nu_ventaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTiendaTest.VentasWS.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_fecha {
            get {
                return this.dt_fechaField;
            }
            set {
                if ((this.dt_fechaField.Equals(value) != true)) {
                    this.dt_fechaField = value;
                    this.RaisePropertyChanged("dt_fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTiendaTest.VentasWS.Cliente nu_ruc {
            get {
                return this.nu_rucField;
            }
            set {
                if ((object.ReferenceEquals(this.nu_rucField, value) != true)) {
                    this.nu_rucField = value;
                    this.RaisePropertyChanged("nu_ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nu_total {
            get {
                return this.nu_totalField;
            }
            set {
                if ((this.nu_totalField.Equals(value) != true)) {
                    this.nu_totalField = value;
                    this.RaisePropertyChanged("nu_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nu_venta {
            get {
                return this.nu_ventaField;
            }
            set {
                if ((this.nu_ventaField.Equals(value) != true)) {
                    this.nu_ventaField = value;
                    this.RaisePropertyChanged("nu_venta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nu_rucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tx_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tx_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nu_ruc {
            get {
                return this.nu_rucField;
            }
            set {
                if ((object.ReferenceEquals(this.nu_rucField, value) != true)) {
                    this.nu_rucField = value;
                    this.RaisePropertyChanged("nu_ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tx_direccion {
            get {
                return this.tx_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.tx_direccionField, value) != true)) {
                    this.tx_direccionField = value;
                    this.RaisePropertyChanged("tx_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tx_nombre {
            get {
                return this.tx_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.tx_nombreField, value) != true)) {
                    this.tx_nombreField = value;
                    this.RaisePropertyChanged("tx_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteInexistenteError", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Errores")]
    [System.SerializableAttribute()]
    public partial class ClienteInexistenteError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int co_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nu_precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tx_descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int co_producto {
            get {
                return this.co_productoField;
            }
            set {
                if ((this.co_productoField.Equals(value) != true)) {
                    this.co_productoField = value;
                    this.RaisePropertyChanged("co_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nu_precio {
            get {
                return this.nu_precioField;
            }
            set {
                if ((this.nu_precioField.Equals(value) != true)) {
                    this.nu_precioField = value;
                    this.RaisePropertyChanged("nu_precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tx_descripcion {
            get {
                return this.tx_descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.tx_descripcionField, value) != true)) {
                    this.tx_descripcionField = value;
                    this.RaisePropertyChanged("tx_descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentasWS.IGestionDeVentaService")]
    public interface IGestionDeVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/Vender", ReplyAction="http://tempuri.org/IGestionDeVentaService/VenderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTiendaTest.VentasWS.ClienteInexistenteError), Action="http://tempuri.org/IGestionDeVentaService/VenderClienteInexistenteErrorFault", Name="ClienteInexistenteError", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaServices.Errores")]
        WCFTiendaTest.VentasWS.Venta Vender(string nu_ruc, WCFTiendaTest.VentasWS.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/Vender", ReplyAction="http://tempuri.org/IGestionDeVentaService/VenderResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Venta> VenderAsync(string nu_ruc, WCFTiendaTest.VentasWS.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ObtenerCliente", ReplyAction="http://tempuri.org/IGestionDeVentaService/ObtenerClienteResponse")]
        WCFTiendaTest.VentasWS.Cliente ObtenerCliente(string nu_ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ObtenerCliente", ReplyAction="http://tempuri.org/IGestionDeVentaService/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Cliente> ObtenerClienteAsync(string nu_ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ObtenerProducto", ReplyAction="http://tempuri.org/IGestionDeVentaService/ObtenerProductoResponse")]
        WCFTiendaTest.VentasWS.Producto ObtenerProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ObtenerProducto", ReplyAction="http://tempuri.org/IGestionDeVentaService/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Producto> ObtenerProductoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ListarVentas", ReplyAction="http://tempuri.org/IGestionDeVentaService/ListarVentasResponse")]
        WCFTiendaTest.VentasWS.Venta[] ListarVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDeVentaService/ListarVentas", ReplyAction="http://tempuri.org/IGestionDeVentaService/ListarVentasResponse")]
        System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Venta[]> ListarVentasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionDeVentaServiceChannel : WCFTiendaTest.VentasWS.IGestionDeVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionDeVentaServiceClient : System.ServiceModel.ClientBase<WCFTiendaTest.VentasWS.IGestionDeVentaService>, WCFTiendaTest.VentasWS.IGestionDeVentaService {
        
        public GestionDeVentaServiceClient() {
        }
        
        public GestionDeVentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionDeVentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDeVentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDeVentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTiendaTest.VentasWS.Venta Vender(string nu_ruc, WCFTiendaTest.VentasWS.Item[] items) {
            return base.Channel.Vender(nu_ruc, items);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Venta> VenderAsync(string nu_ruc, WCFTiendaTest.VentasWS.Item[] items) {
            return base.Channel.VenderAsync(nu_ruc, items);
        }
        
        public WCFTiendaTest.VentasWS.Cliente ObtenerCliente(string nu_ruc) {
            return base.Channel.ObtenerCliente(nu_ruc);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Cliente> ObtenerClienteAsync(string nu_ruc) {
            return base.Channel.ObtenerClienteAsync(nu_ruc);
        }
        
        public WCFTiendaTest.VentasWS.Producto ObtenerProducto(int codigo) {
            return base.Channel.ObtenerProducto(codigo);
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Producto> ObtenerProductoAsync(int codigo) {
            return base.Channel.ObtenerProductoAsync(codigo);
        }
        
        public WCFTiendaTest.VentasWS.Venta[] ListarVentas() {
            return base.Channel.ListarVentas();
        }
        
        public System.Threading.Tasks.Task<WCFTiendaTest.VentasWS.Venta[]> ListarVentasAsync() {
            return base.Channel.ListarVentasAsync();
        }
    }
}
